### PR TITLE
Implements SigV4-signed requests in getAuthorizedURL()

### PR DESCRIPTION
**Pull request by sbleon**
This replaces PR #22 and addresses issue #18.

This commit builds on top of #26, and includes its commits, so that one should
be reviewed and merged first.

### CODE REVIEW

**Comment by sbleon** [comment]
@lmajano @bdw429s, we've been using this branch in production for months now, and it's been working great. What is the process for merging to master and cutting a new release?

**Comment by lmajano** [comment]
Hi @sbleon I have this under my radar now. Unfortunately. time has escaped me this time around for this module. However, I have it scheduled now.  I will contact you for some feedback on several more issues. Thanks for your patience and help.  I really appreciate it.

**Comment by lmajano** [comment]
@sbleon we ahve found an issue updating our travis builds to use `focal` instead of the old `trusty` edition that we need assitance on.  Basically ACF borks on using the `ram:///` storage 

image

We are trying to find out if it's an Adobe issue or we are missing a dependency for linux.  Thoughts?

**Comment by sbleon** [comment]
I saw that you just removed the RAM disk usage
in a3a95c235cd7f5e1e6111a429cf348d3f0a86d45. Did that resolve the CI
problem?

**Pull request merged**
