### PR TITLE
Switch to v4 signatures

### PR DESCRIPTION
**Pull request by elpete**
This pull request switches the signature method to [v4 signatures](http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html).  The signature calculation is now encapsulated in the `Sv4Util.cfc`.

Additionally, this pull request adds some basic test coverage to make sure that the changes made didn't break anything.

### CODE REVIEW

**Comment by lmajano** [comment]
@elpete Everything looks great.  Question, how much more would it take to convert all to script?

**Comment by elpete** [comment]
Sure thing. Should take less than an hour.

One more question — should we pull out the `AWSv4SignatureUtil` to its own
module?

Cheers,
Eric

**Comment by lmajano** [comment]
Yes. Let’s do that.

Luis Majano
CEO
Ortus Solutions, Corp
www.ortussolutions.com
P/F: 1-888-557-8057
________________________________

**Comment by elpete** [comment]
Convert to script is done.  I figure we'll pull out the signature module the next time we need it.

**Pull request merged**
