### PR TITLE
Document dev setup and create a start script that passes env vars to test engine

### PR DESCRIPTION
**Pull request by sbleon**

### CODE REVIEW

**Comment by sbleon** [comment]
This replaces my old PR #20.

**Comment by jordanclark** [comment]
@sbleon have you checked out the addon module commandbox-dotenv which will read the .env file and add those variables into the environment when commandbox starts up a server ?

**Comment by sbleon** [comment]
I hadn't heard of it, but it sounds like potentially a good fit. I'll check
it out.

**Comment by sbleon** [comment]
@jordanclark I switched to `commandbox-dotenv`. Thanks for the tip!

There's now less *nix-specific stuff in `test-harness/start`. @lmajano I think this is ready to be merged.

**Comment by lmajano** [comment]
@sbleon everything looks good. However, I would remove the .start file as it only will help unix based or mac based folks.  How about we add something like we just did with ColdBox.  This way you can just say: `box run-script start:lucee5` or `box run-script start:2016` etc?  

```
"scripts":{
		"format": "cfformat run system/**/*.cfc,tests/specs/**/*.cfc --overwrite",
        "format:watch": "cfformat watch system/**/*.cfc,tests/specs/**/*.cfc",
        "format:check": "cfformat check system/**/*.cfc,tests/specs/**/*.cfc",
		"start:lucee" : "server start serverConfigFile='server-lucee@5.json'",
		"start:2016" : "server start serverConfigFile='server-adobe@2016.json'",
		"start:2018" : "server start serverConfigFile='server-adobe@2018.json'",
		"log:lucee" : "server log coldbox-lucee@5 --follow",
		"log:2016" : "server log coldbox-adobe@2016 --follow",
		"log:2018" : "server log coldbox-adobe@2018 --follow"
	}
```

**Comment by sbleon** [comment]
I've added the new `script` entries and removed the `start` file. It would
be great if we could somehow also override `box start` so that it
defaulted to using the Lucee 5 `serverConfigFile`, but I'm not sure if
that's possible.

**Comment by sbleon** [comment]
@lmajano I've fixed the Travis build in this branch, and improved my docs a little bit. I think this is ready to merge now.

**Comment by sbleon** [comment]
@lmajano @bdw429s I'm circling back to this PR since at least one person has found my subsequent, dependent PRs useful. Can we merge this (non-controversial, I think) PR so I can rebase the next one on it and make some more progress?

**Comment by lmajano** [comment]
Sorry about the delay, a lot got in the way, revisiting all of this.

**Pull request merged**
