### PR TITLE
Unit tests for Sv4Util and getAuthenticatedURL()

### PR DESCRIPTION
**Pull request by sbleon**
This replaces #21.

### CODE REVIEW

**Comment by sbleon** [comment]
@lmajano, this is an all-test PR, and I think it's good to go.

**Comment by lmajano** [comment]
looks good, can you apply the formatting only :)

**Comment by sbleon** [comment]
I tried (after fixing the `format` script syntax), and cfformat failed to
format the files:

```

$ box run-script format


Running package script [format].

> cfformat models/**/*.cfc,test-harness/tests/**/*.cfc,*.cfc --overwrite

 × | Formatting components...

   |---------------------------------------

   | /Users/leon/code/s3sdk/models/AmazonS3.cfc

   | /Users/leon/code/s3sdk/models/Sv4Util.cfc

   | /Users/leon/code/s3sdk/test-harness/tests/specs/AmazonS3Spec.cfc

   | /Users/leon/code/s3sdk/ModuleConfig.cfc

   | /Users/leon/code/s3sdk/test-harness/tests/Application.cfc

   | /Users/leon/code/s3sdk/test-harness/tests/specs/Sv4UtilSpec.cfc

   |---------------------------------------

Files formatted: 0

The following files were unable to be formatted:




  /Users/leon/code/s3sdk/models/AmazonS3.cfc

  /Users/leon/code/s3sdk/models/Sv4Util.cfc

  /Users/leon/code/s3sdk/test-harness/tests/specs/AmazonS3Spec.cfc

  /Users/leon/code/s3sdk/ModuleConfig.cfc

  /Users/leon/code/s3sdk/test-harness/tests/Application.cfc

  /Users/leon/code/s3sdk/test-harness/tests/specs/Sv4UtilSpec.cfc

```

**Comment by sbleon** [comment]
@lmajano This has been rebased and should be good to go.

PS. Thanks for merging the other PR!

**Pull request merged**
