### PR TITLE
Adobe Coldfusion 2021 compatibility

### PR DESCRIPTION
**Pull request by sbleon**

### CODE REVIEW

**Comment by sbleon** [comment]
@bdw429s @jclausen @lmajano can y'all cut a new release? The library did not work correctly with CF2021 before I merged this.

**Comment by lmajano** [comment]
Thanks for this @sbleon . Updated changelogs, readme and deployed to travis for release.

**Comment by lmajano** [comment]
https://travis-ci.com/github/coldbox-modules/s3sdk/builds/221059979

**Comment by sbleon** [comment]
The tests all passed, but the build failed to deploy:
```
Install deployment dependencies
Authenticate deployment
Authenticated as %s
Access token required (ArgumentError)
failed to deploy
```

**Comment by lmajano** [comment]
Yes, we rotated keys. I will update right now, however, the build actually did publish, it was the github integrations that failed.  So all good there.

**Comment by sbleon** [comment]
Great! v4.7.0 is working nicely in ACF2021. Thanks!

**Pull request merged**
