### PR TITLE
Fix mixed whitespace

### PR DESCRIPTION
**Pull request by sbleon**

### CODE REVIEW

**Comment by sbleon** [comment]
Hi, @lmajano. I'm hoping you can help here. All Travis builds are failing with "lucee.runtime.exp.CustomTypeException: Could not find a Java System property or Env setting with key [AWS_ACCESS_KEY]."

I assume the Travis builds were working at some point. Do you know how the environment variables are supposed to be set up in Travis? (I'm pretty sure we don't want to commit any real AWS access keys to source control.)

**Comment by lmajano** [comment]
Hi @sbleon thanks for the pulls. Revising them.  Can you make sure you update your pull with the following:

1. We use tabbed spacing, look in editorconfig for it.
2. Use our latest updated `.cfformat.json` for formatting the code https://github.com/Ortus-Solutions/coding-standards/blob/master/.cfformat.json

**Comment by sbleon** [comment]
Thanks, Luis. Sorry that I missed the project's code standards!

I've re-updated the whitespace, although only in the files I'm going to be touching, because I don't have a good automated way to do it for all of the files in the project. This will at least make the following PRs have clean, minimal diffs with no whitespace change noise.

I have not been able to reformat the files, because cfformat is failing without providing any actionable feedback. I'm hoping we can forego reformatting at this time and just merge the whitespace changes.
```
CommandBox> cfformat models/**/*.cfc,test-harness/tests/**/*.cfc,*.cfc --overwrite
 × | Formatting components...
   |---------------------------------------
   | /Users/leon/code/s3sdk/models/AmazonS3.cfc
   | /Users/leon/code/s3sdk/models/Sv4Util.cfc
   | /Users/leon/code/s3sdk/test-harness/tests/specs/AmazonS3Spec.cfc
   | /Users/leon/code/s3sdk/ModuleConfig.cfc
   | /Users/leon/code/s3sdk/test-harness/tests/Application.cfc
   |---------------------------------------
Files formatted: 0
The following files were unable to be formatted:                                                                                                                                                                                                  
  /Users/leon/code/s3sdk/models/AmazonS3.cfc
  /Users/leon/code/s3sdk/models/Sv4Util.cfc
  /Users/leon/code/s3sdk/test-harness/tests/specs/AmazonS3Spec.cfc
  /Users/leon/code/s3sdk/ModuleConfig.cfc
  /Users/leon/code/s3sdk/test-harness/tests/Application.cfc
```

**Comment by lmajano** [comment]
Ok, let's not worry about cfformat for now.

**Comment by lmajano** [comment]
Ok, updated it so the env vars can be read. Can you rebase and resend please

**Comment by sbleon** [comment]
Luis, it looks like we've got some more test suite issues. Is it possible that the AWS_DOMAIN env var is empty in the Travis env?
```
lucee.runtime.exp.NativeException: Host name may not be empty
	at org.apache.http.util.Args.containsNoBlanks(Args.java:84)
	at org.apache.http.HttpHost.<init>(HttpHost.java:80)
	at lucee.runtime.tag.Http._doEndTag(Http.java:757)
	at lucee.runtime.tag.Http.doEndTag(Http.java:689)
	at models.amazons3_cfc$cf.udfCall4(/s3sdk/models/AmazonS3.cfc:911)
	at models.amazons3_cfc$cf.udfCall(/s3sdk/models/AmazonS3.cfc)
```

**Comment by lmajano** [comment]
@sbleon I am testing it out again, not sure why it is not working.

**Comment by lmajano** [comment]
Can you rebase and try again please, sorry about this, but dealing with s3 is not always nice

**Comment by sbleon** [comment]
Done! We'll see what happens this time...

**Comment by sbleon** [comment]
Failed, due to apparently blank access key:

>-> S3SDKError:Error making Amazon REST Call: Code: AuthorizationHeaderMalformed\nMessage: The authorization header is malformed; a non-empty Access Key (AKID) must be provided in the credential.\nRequestId: AED47220D0049337\nHostId: ukQze/OqbDegRmrDUeEvkr5sEMQ/ekTgN+OuMds5kBrAOBqA3dz3+zy+zqfoE/yOkCcMg+M4Yl0=:"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; a non-empty Access Key (AKID) must be provided in the credential.</Message><RequestId>AED47220D0049337</RequestId><HostId>ukQze/OqbDegRmrDUeEvkr5sEMQ/ekTgN+OuMds5kBrAOBqA3dz3+zy+zqfoE/yOkCcMg+M4Yl0=</HostId></Error>"

I don't see AWS_ACCESS_KEY and AWS_ACCESS_SECRET being set in the Travis job output. I do see AWS_REGION and AWS_DOMAIN there, though. https://travis-ci.org/github/coldbox-modules/s3sdk/jobs/671800076?utm_medium=notification&utm_source=github_status

**Comment by lmajano** [comment]
I am so sorry about this @sbleon travis is behaving poorly on this.

**Comment by lmajano** [comment]
The other keys are not visible because they are secret.

**Comment by lmajano** [comment]
@elpete can you help me please, I have no clue why this is failing. It doesn't fail on the main branches.

**Comment by elpete** [comment]
Secret and encrypted keys are only available from branches of the original repo, not PRs.  Otherwise, a malicious actor could add `echo $SUPER_SECRET_KEY` to the `.travis.yml` of a pull request and steal our secrets.

**Comment by sbleon** [comment]
So CI tests can never run successfully on PRs from forks. That's unfortunate, but makes sense.

I'd like to have CI work for my PRs. Do y'all want to give me everything-but-development-branch access to this repo?  If not, that's OK. I can just run the tests locally and you can either trust me when I say they're green or verify them yourself.

**Comment by lmajano** [comment]
Ok, here is the deal @sbleon I have added you as a maintainer with us in the repo. This will allow you to push branches into the repo which will run against travis using our credentials.  This way the procedure to follow is the same. Push your branch into the repo and send a pull request into `development`.

Now to the good news: You are part of the team now :)

**Comment by lmajano** [comment]
So for now, you will have to close these PRs and re-send, but using the branching strategy on the repo

**Comment by sbleon** [comment]
Awesome! Thanks for putting your trust in me! I'll use this package on at least a couple of projects, so I'm definitely interested in making sure it continues to work well.

**Pull request closed without merging**
